### PR TITLE
Improve formatting and make compatible with authblk

### PR DESCRIPTION
**Pull request by cviner**
Thanks so much for making this package! I recently wanted to use it and needed to make these changes, which I hope might be useful for others. It would need to be properly incorporated and re-packaged—I regret that I am unable to do so.

These changes incorporate and make additional adaptations from [TeX.SE](https://tex.stackexchange.com/a/454793/134641), to ensure compatibility with `authblk`.

Logo positioning and formatting is additionally improved.

### CODE REVIEW

**Comment by duetosymmetry** [comment]
Hi @cviner, thanks for your PR! Can you (or another author on TeX.SE) explain how this change works? I don't have any experience with \newrobustcmd (from etoolbox?), or using "remember picture" in tikz.

Is this change strictly safer than the previous code?

Why was the \texorpdfstring removed (which was there to avoid complaints when the contents of \author is captured into PDF metadata)?

**Comment by cviner** [comment]
`\newrobustcmd` is indeed from [`etoolbox`](https://ctan.org/pkg/etoolbox). It prevents the command from being fragile (as described [here](https://tex.stackexchange.com/a/4747/134641)), effectively making it as though it had been prefaced by `\protect`, which is needed for use in `authblk`.  It is indeed strictly safer than before.

The `remember picture` aspect was not something I came up with, but rather used by the more recent [TeX.SE](https://tex.stackexchange.com/a/454793/134641) revision I adapted. My understanding is that it effectively allows nodes to be referenced outside the current picture. My understanding is that this allows for improved positioning, in conjunction with `overlay`, which prevents the current scope from being used for the bounding box calculation. Without these changes, with multiple authors (at least for me with `authblk`), the entire remaining line and page can get cutoff, after the first use of the new command.

I did not intend to remove `\texorpdfstring`. It wasn't present in the code I adapted. I have added it back in, but not tested it—apologies for the oversight.

**Comment by duetosymmetry** [comment]
Ok, I'm going to have to do some testing to figure out whether `\texorpdfstring` is needed if `\newrobustcmd` is used, try to understand how the dimensions of the logo are calculated, etc.

BTW, could you please squash this PR down to one commit?

And ideally, it should edit the `.dtx` file instead of the `.sty` file directly. The latter should be generated from the former, and both changes should be included in the commit. The change to the `.dtx` should include updating the date, incrementing the version, and adding an entry for this change into the list of changes.

**Comment by cviner** [comment]
It will still be needed—the use of the robust command will not change anything WRT that fixing the metadata warning.

You should be able to squash my commits during an eventual merge, by selecting that option within GitHub.

I have no experience with DTX files nor generating STY files from them. I regret that I don't have any more time to work on this right now.

**Comment by tobiasBora** [comment]
I can also confirm that using `\newrobustcmd` instead of `\newcommand` solves the compilation in the llncs class (used notably in computer science/cryptography). However, this specific code is kind of strange, it turns the `i` upside down:
image

However, using `\newrobustcmd` with the current code works perfectly:
```
\RequirePackage{etoolbox}
% [....]
\newrobustcmd\orcidlink[1]{\href{https://orcid.org/#1}{\mbox{\scalerel*{
        \begin{tikzpicture}[yscale=-1,transform shape]
          \pic{orcidlogo};
        \end{tikzpicture}
      }{|}}}{}}
```
I guess it is safe to use `\newrobustcmd` like that.

**Comment by duetosymmetry** [comment]
@tobiasBora Thanks for this extra info. When you say "this specific code", are you referring to @cviner's PR? I see in their PR that they have removed the `yscale=-1` which is why the logo has flipped upside down.

@cviner Will you rewrite your commit so that it is as suggested by @tobiasBora (and so that it affects both the .dtx and .sty files)? And please squash all commits so there is only 1 in the PR. Let me know if you can do this or not.

**Comment by cviner** [comment]
I regret that I will not be able to so.

**Comment by duetosymmetry** [comment]
@cviner @tobiasBora I have pushed to your branch (it's enabled for this repo) with the necessary changed. Can you please confirm if this code works with `authblk` and `llncs`?

**Comment by cviner** [comment]
This appears to have undone my main TikZ changes. Without the use of `overlay` in particular, this will not work with `authblk`.

**Comment by duetosymmetry** [comment]
Yikes, sorry about that! I'll revisit this after my lecture.

**Comment by duetosymmetry** [comment]
@cviner, can you please post a gist of a minimal authblk usage where overlay is required to move the icon correctly?

**Comment by cviner** [comment]
The original [TeX.SE](https://tex.stackexchange.com/a/454793/134641) post is quite minimal. You can see the issue in the original post. With more authors the issue can become more severe, cutting off the entire line. Hopefully that example should suffice.

**Comment by duetosymmetry** [comment]
After some experimentation I've determined that the problem is not coming from Tikz, but rather from `\scalerel*`. The `overlay` and `remember picture` hacks should not be needed. I especially do not want to use the solution posted there on TeX.SE because it hardcodes lengths, which is unacceptable because different packages use different default font sizes. What I need to figure out now is how to get the current text height, and make Tikz figure out how to scale down to that height.

**Comment by duetosymmetry** [comment]
Sorry about all my thrashing about. @cviner and @tobiasBora, can you confirm that this new code works with both of your document classes? I tested it myself, but it's always good to get more testing.

**Comment by cviner** [comment]
This works perfectly for me. Glad to have this improved solution—thanks!

My only suggestion would be to add `\hspace{0.05em}%`, after `\end{tikzpicture}%`. I find that the logo is otherwise too close to my footnotes.

**Comment by duetosymmetry** [comment]
@cviner I agree that the spacing is very tight, though I'm not sure that I should assume how to manage the spacing for the end user. Do you know of any recommendations regarding logos that are inline in text?

**Comment by cviner** [comment]
Unfortunately not!

**Comment by tobiasBora** [comment]
I can confirm it works greatly, thanks a lot! I can also confirm that a small spacing like the one proposed by @cviner gives a nicer output (but you need to put the star, like `\hspace*{0.05em}` for it to work.

**Pull request merged**
